/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
          "inverse-surface": "#dde4dd",
          "surface-container-low": "#161d19",
          "inverse-on-surface": "#2b322d",
          "on-tertiary-fixed": "#410005",
          "tertiary-fixed-dim": "#ffb3af",
          "on-tertiary": "#650911",
          "secondary-fixed-dim": "#c7c5ce",
          "on-primary-container": "#00422b",
          "on-primary-fixed-variant": "#005236",
          "surface-container-lowest": "#09100c",
          "secondary-container": "#4b4b52",
          "on-surface-variant": "#bbcabf",
          "outline-variant": "#3c4a42",
          "on-surface": "#dde4dd",
          "primary": "#10b981",
          "surface-container-highest": "#2f3632",
          "outline": "#86948a",
          "surface-tint": "#10b981",
          "on-secondary-fixed": "#1b1b21",
          "surface-dim": "#0e1511",
          "tertiary-container": "#fc7c78",
          "on-error": "#690005",
          "inverse-primary": "#006c49",
          "on-error-container": "#ffdad6",
          "on-tertiary-fixed-variant": "#842225",
          "background": "#09090b",
          "on-secondary-fixed-variant": "#46464d",
          "on-primary": "#003824",
          "surface-variant": "#2f3632",
          "tertiary": "#ffb3af",
          "surface-container-high": "#242c27",
          "surface": "#0e1511",
          "on-secondary": "#303037",
          "secondary": "#c7c5ce",
          "on-primary-fixed": "#002113",
          "error": "#ffb4ab",
          "primary-fixed-dim": "#4edea3",
          "tertiary-fixed": "#ffdad7",
          "on-background": "#dde4dd",
          "error-container": "#93000a",
          "on-secondary-container": "#bcbbc3",
          "primary-container": "#10b981",
          "primary-fixed": "#6ffbbe",
          "secondary-fixed": "#e3e1ea",
          "on-tertiary-container": "#711419",
          "surface-bright": "#343b36",
          "surface-container": "#1a211d"
      },
      borderRadius: {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      spacing: {
          "xl": "40px",
          "gutter": "24px",
          "base": "4px",
          "md": "16px",
          "sm": "8px",
          "lg": "24px",
          "container-max": "1200px",
          "xs": "4px"
      },
      fontFamily: {
          "headline-md": ["Geist"],
          "label-uppercase": ["Geist"],
          "body-lg": ["Inter"],
          "display-lg": ["Geist"],
          "body-sm": ["Inter"],
          "code": ["Geist"],
          "display-lg-mobile": ["Geist"]
      },
      fontSize: {
          "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
          "label-uppercase": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "body-lg": ["16px", {"lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400"}],
          "display-lg": ["48px", {"lineHeight": "52px", "letterSpacing": "-0.04em", "fontWeight": "700"}],
          "body-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400"}],
          "code": ["13px", {"lineHeight": "20px", "fontWeight": "400"}],
          "display-lg-mobile": ["32px", {"lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
